kumuluzee:
  name: statistic-services
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8084
    http:
      port: 8084
  datasources:
    - jndi-name: jdbc/StatisticsDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/nejc
      username: postgres
      password: postgres
      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/StatisticsDS
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  metrics:
    web-instrumentation:
      - name: statistics-endpoint
        url-pattern: /v1/statistics/*
  openapi:
    ui:
      enabled: true
app-properties:
  external-services:
    enabled: false
  statistic-service:
    enabled: false
  healthy-service:
    enabled: true
